name: manual_deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'tag'
        required: true
        default: 'i-need-this-now'

jobs:
  build-and-push-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build bf image
        run: |
          docker build \
          -t botfront/botfront:${{github.event.inputs.tag}} \
          .
      - name: log in
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: push
        run: |
          docker push botfront/botfront:${{github.event.inputs.tag}}
